### ISSUE TITLE
sticky view超出屏幕高度应该怎样处理呢？

### ISSUE THREAD

**Issue by zhyihui** [xmuSistone/android-sticky-viewpager#1]
请问如果ViewPager上面的StickyView部分超过了一屏的高度，应该怎样处理呢？我试了下，现在无法正确处理，而我水平也不好，没有想出什么办法，不知道你有什么办法分享一下。
类似于商城App的商品详情页面，如下图：
![qq 20150604205446](https://cloud.githubusercontent.com/assets/4401837/7984511/8f1f9280-0afc-11e5-99f0-e8203ffd8ec3.png)

**Comment by xmuSistone** [comment]
你好，
      如果viewpager上面的stickyView超过了屏幕的高度，这个需要特殊处理的。
      android所有的widget在渲染时，onMeasure传入的两个参数，一个是宽度，一个是高度。那第二个参数“heightMeasureSpec”是不会超过屏幕高度的。所以，如果超过屏幕高度的话，需要复写onMeasure方法，并将第二个参数调成你想要的高度。这样就不会影响高度的设置。
      代码很简单，自定义一个LinearLayout：
        @Override
	protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
		super.onMeasure(widthMeasureSpec, AppDetailFragment.STICKY_HEIGHT2); // 请注意第二个参数
	}

       


       我看了你要实现的效果，然后我做了一些改动，apk在附件，你可以下载看看。代码也附件传给你。


       然后，滑动停止时，粘到的位置也稍作了调整，但是仍然会有一些其它的问题，等待你自己去fix。要注意的是，stickyView左右滑动时，依然能触发viewpager的滑动，请自己对OverScreenLayout的dispatchTouchEvent进行复写，以禁止左右滑动带来viewpager的改动。


      如还有其它问题，欢迎随时再email给我~~




      -- 祝工作顺利












------------------ 原始邮件 ------------------
发件人: "yihui.zh";<notifications@github.com>;
发送时间: 2015年6月4日(星期四) 晚上9:00
收件人: "xmuSistone/android-sticky-viewpager"<android-sticky-viewpager@noreply.github.com>; 

主题: [android-sticky-viewpager] sticky view超出屏幕高度应该怎样处理呢？ (#1)




请问如果ViewPager上面的StickyView部分超过了一屏的高度，应该怎样处理呢？我试了下，现在无法正确处理，而我水平也不好，没有想出什么办法，不知道你有什么办法分享一下。
 类似于商城App的商品详情页面，如下图：

**Comment by zhyihui** [comment]
xmuSistone
    你好！
    非常感谢你的回复
    你说的内容我暂时还不能完全消化，我会尝试去理解！
    另外，你说的附件我没有在邮件中找到，请问你放在哪了？
                                                再度表示感谢！
                                                期盼回复！
