### ISSUE TITLE
全屏的ViewPager会有一些问题

### ISSUE THREAD

**Issue by xu6148152** [xmuSistone/android-sticky-viewpager#3]
这种方案其实就没涉及到自定义控件。

1. 当你左右过程滑动中，你会看到另一个页面的内容上部是一片空白

2. 当如果整合进去下拉刷新，你回发现问题更麻烦了。如果用SwipeRefreshLayout可以解决。

**Comment by xmuSistone** [comment]
后面我跟踪一下这个问题

**Comment by xu6148152** [comment]
sorry,我说的第一点可能不会出现，因为你每次切换TAB，并且滑动的话，会把另一边的复位。这种方案可能造成的问题是，当用户向上滚动，然后切换TAB，并且向下滚动，右侧的内容就自动跑到最顶部了。。。这体验可能有点差。

**Comment by xmuSistone** [comment]
scrollView复位是有选择的复位，只在两个tab的stickyView位置无法契合时，才做的调整。这个无法避免。你可以去看下其它的类似的github项目，他们是用分治法做的，里面夹杂大量的onTouch分发与拦截，但是也无法避免要将scrollView的位置强制调整。如果说影响了用户体验，这个得看产品经理是否会妥协了。

**Comment by xu6148152** [comment]
目前比较好的实现方式可以看这个
https://github.com/ksoichiro/Android-ObservableScrollView/

当然如果用Design support library 中的CoordinateLayout的话，也可以比较轻松的实现类似效果，但是必须保证，它的子VIEW都实现了ViewParent这个接口。

目前你这个效果还算可以，但有一定问题。如加入下拉刷新的话(不是SwipeRefreshLayout)，可以这种思路就比较难以整合了。所以其实较好的方案，个人觉得还是应该滚动整个ViewPager，这样它的内容也会跟随整体滚动。

**Comment by xu6148152** [comment]
去年的时候，我最初看到的效果是这个

https://github.com/kmshack/Android-ParallaxHeaderViewPager
它就会存在我在一楼提到的第一点问题。
目前采取类似的方案还是蛮多的。但效果并不是最佳。
美团的做法似乎不是这样的，应该采取的是自定义控件，来处理各种事件，比较麻烦。
这个https://github.com/chenupt/DragTopLayout也是一种解决方案，但都有缺陷。

**Comment by xmuSistone** [comment]
恩，你发的这个project确实很不错。回头我也研究下看看。之前我一直解决不了的一个问题，是上下view之间的无缝滑动连接。后面我瞅瞅~

**Comment by xu6148152** [comment]
是的，我最早也是碰到这个问题。
目前最完美的解决方案应该就是采用Design support library中的CoordinateLayout来处理了。

**Comment by xmuSistone** [comment]
恩好的。多谢告知，学习了

**Comment by 401885064** [comment]
谢谢，刚刚看了这个demo，太复杂了。项目赶，有没有其他好的推荐？

**Comment by xmuSistone** [comment]
可以看这个，但是修改需要你自己定制了。我改了两天。哈哈哈
https://github.com/w446108264/StickyHeaderViewPager

**Comment by 401885064** [comment]
谢谢   xmuSistone ，  我研究下！

花了一个早上用了https://github.com/chenupt/DragTopLayout这个。。。。小米手机没问题，LG G3手机出现滑动问题。。。坑啊。。。而且貌似作者已经10个月没有更新bug了。。。。  后来者最后不要用
